name: Release

on:
  push:
    tags:
      - "v*.."

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build pytest twine wheel setuptools-scm>=6.2

      - name: Build package
        run: python -m build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lib-version-dist
          path: dist/

      - name: Extract version from tag
        id: get_tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT 

      - name: Update tag
        id: updated_tag
        run: |
          git fetch --all
          git checkout main
          
          IFS='.' read -r MAJOR MINOR PATCH <<< "${{steps.get_tag.outputs.VERSION}}"
          NEW_PATCH=$((PATCH + 1))
          echo "v$MAJOR.$MINOR.${NEW_PATCH}-pre" > VERSION
          
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
          git add VERSION
          git commit -m "Bump version"
          git push origin HEAD:main